# Generated by Django 3.0.4 on 2021-10-24 15:12

from django.db import migrations, models
import django.db.models.deletion
import justapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_students', models.PositiveSmallIntegerField(default=1)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('studentid', models.CharField(default=justapp.models.unique_rand, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justapp.School', validators=[justapp.models.is_not_reach_max_students])),
            ],
        ),
    ]
